'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useRouter } from "@/i18n/navigation";
import {
    Bot, ChevronDown, Clock, AlertTriangle,
    Send, Droplet, MapPin
} from 'lucide-react';
import { toast } from 'sonner';
import { useRequestFormStore } from '@/store/request-form.store'; // Also let's optionally save it to store

export default function AIBloodAssistant() {
    const router = useRouter();
    const { updateStep1, updateStep2 } = useRequestFormStore();

    const [currentStep, setCurrentStep] = useState(1);
    const [bloodGroup, setBloodGroup] = useState('');
    const [city, setCity] = useState('');
    const [urgency, setUrgency] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const chatEndRef = useRef<HTMLDivElement>(null);

    const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

    // Scroll to bottom when step advances
    useEffect(() => {
        chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [currentStep, bloodGroup, city, urgency]);

    const handleBloodGroupSelect = (bg: string) => {
        setBloodGroup(bg);
        // Slight delay to simulate bot typing/thinking
        setTimeout(() => setCurrentStep(2), 600);
    };

    const handleCitySelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const selectedCity = e.target.value;
        if (!selectedCity) return;
        setCity(selectedCity);
        setTimeout(() => setCurrentStep(3), 600);
    };

    const handleUrgencySelect = (urg: string) => {
        setUrgency(urg);
        setTimeout(() => setCurrentStep(4), 600);
    };

    const handleSubmit = async () => {
        setIsSubmitting(true);

        // Save to the global store just in case it's used by the Success page
        updateStep1({ bloodGroup: bloodGroup as any, urgency: urgency.toLowerCase() as any, units: 1, patientName: '', hospitalName: '' });
        updateStep2({ city: city, hospitalArea: '', requirementType: urgency as 'Urgent' | 'Scheduled', deadline: '' });

        try {
            // Simulate backend generation/broadcast
            await new Promise((resolve) => setTimeout(resolve, 2000));
            toast.success('Request generated by AI and broadcasted successfully!');
            router.push('/requests/create/success');
        } catch (error) {
            toast.error('Failed to broadcast request. Please try again.');
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="bg-[#FAFAFA] font-sans text-slate-900 flex flex-col selection:bg-red-100 selection:text-red-900 min-h-screen w-full">
            {/* Main Content Area */}
            <main className="flex-1 max-w-3xl mx-auto w-full px-4 sm:px-6 py-10 flex flex-col">

                {/* Page Titles */}
                <div className="mb-8 text-center sm:text-left">
                    <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight mb-2">AI Blood Assistant</h1>
                    <p className="text-slate-500 font-medium">Guided request creation for faster donor matching</p>
                </div>

                {/* Chat Interface Container */}
                <div className="bg-white rounded-[2rem] border border-slate-100 shadow-[0_4px_20px_-4px_rgba(0,0,0,0.02)] flex flex-col relative overflow-hidden flex-1 mb-8">

                    {/* Scrollable Chat Area */}
                    <div className="p-6 sm:p-8 space-y-8 pb-48 overflow-y-auto">

                        {/* STEP 1: Blood Group */}
                        <div className={`flex gap-4 max-w-2xl transition-all duration-500 opacity-100 translate-y-0`}>
                            <div className="w-10 h-10 rounded-full bg-red-50 flex items-center justify-center shrink-0 mt-6 shadow-sm">
                                <Bot size={20} className="text-[#C41C1C]" />
                            </div>
                            <div className="space-y-3 flex-1">
                                <span className="text-[10px] font-black text-[#C41C1C] uppercase tracking-widest ml-1">Sehat AI</span>
                                <div className="bg-slate-50 rounded-2xl rounded-tl-sm p-4 text-slate-800 font-medium inline-block w-full sm:w-auto">
                                    Which blood group is required?
                                </div>
                                {/* Options */}
                                {currentStep === 1 && (
                                    <div className="flex flex-wrap gap-2 mt-2 animate-in fade-in slide-in-from-bottom-2 duration-500">
                                        {bloodGroups.map((bg) => (
                                            <button
                                                key={bg}
                                                onClick={() => handleBloodGroupSelect(bg)}
                                                className={`w-12 h-10 rounded-full text-sm font-bold transition-all border ${bloodGroup === bg
                                                        ? 'border-[#C41C1C] text-[#C41C1C] bg-red-50'
                                                        : 'border-slate-200 text-slate-600 hover:border-slate-300 hover:bg-slate-50'
                                                    }`}
                                            >
                                                {bg}
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* USER MSG 1: Selected Blood Group */}
                        {bloodGroup && (
                            <div className="flex gap-4 max-w-2xl ml-auto justify-end animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="space-y-1 flex flex-col items-end">
                                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest mr-1">You</span>
                                    <div className="bg-[#C41C1C] text-white rounded-2xl rounded-tr-sm p-4 min-w-[3.5rem] h-14 flex items-center justify-center text-lg font-black shadow-md shadow-red-200">
                                        {bloodGroup}
                                    </div>
                                </div>
                                <div className="w-10 h-10 rounded-full bg-orange-100 overflow-hidden shrink-0 mt-5 border border-slate-100 shadow-sm flex items-center justify-center text-orange-500 font-bold">
                                    {/* Using initials instead of dicebear simply for reliability, or keep external image */}
                                    You
                                </div>
                            </div>
                        )}

                        {/* STEP 2: City */}
                        {currentStep >= 2 && (
                            <div className="flex gap-4 max-w-2xl animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="w-10 h-10 rounded-full bg-red-50 flex items-center justify-center shrink-0 mt-6 shadow-sm">
                                    <Bot size={20} className="text-[#C41C1C]" />
                                </div>
                                <div className="space-y-3 flex-1 w-full max-w-md">
                                    <span className="text-[10px] font-black text-[#C41C1C] uppercase tracking-widest ml-1">Sehat AI</span>
                                    <div className="bg-slate-50 rounded-2xl rounded-tl-sm p-4 text-slate-800 font-medium inline-block w-full">
                                        In which city is the patient admitted?
                                    </div>
                                    {/* Dropdown */}
                                    {currentStep === 2 && (
                                        <div className="relative flex items-center mt-2 animate-in fade-in duration-500">
                                            <select
                                                value={city}
                                                onChange={handleCitySelect}
                                                className="w-full bg-white border border-slate-200 text-slate-900 rounded-xl py-3 pl-4 pr-10 focus:outline-none focus:ring-2 focus:ring-red-100 focus:border-red-400 transition-all font-medium appearance-none cursor-pointer"
                                            >
                                                <option value="" disabled>Select a city...</option>
                                                <option value="Karachi">Karachi</option>
                                                <option value="Lahore">Lahore</option>
                                                <option value="Islamabad">Islamabad</option>
                                            </select>
                                            <ChevronDown size={18} className="absolute right-4 text-slate-400 pointer-events-none" />
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* USER MSG 2: Selected City */}
                        {currentStep >= 3 && city && (
                            <div className="flex gap-4 max-w-2xl ml-auto justify-end animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="space-y-1 flex flex-col items-end">
                                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest mr-1">You</span>
                                    <div className="bg-[#C41C1C] text-white rounded-2xl rounded-tr-sm p-4 h-14 flex items-center justify-center text-sm font-bold shadow-md shadow-red-200">
                                        {city}
                                    </div>
                                </div>
                                <div className="w-10 h-10 rounded-full bg-orange-100 overflow-hidden shrink-0 mt-5 border border-slate-100 shadow-sm flex items-center justify-center text-orange-500 font-bold">
                                    You
                                </div>
                            </div>
                        )}

                        {/* STEP 3: Urgency */}
                        {currentStep >= 3 && (
                            <div className="flex gap-4 max-w-2xl animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="w-10 h-10 rounded-full bg-red-50 flex items-center justify-center shrink-0 mt-6 shadow-sm">
                                    <Bot size={20} className="text-[#C41C1C]" />
                                </div>
                                <div className="space-y-3 flex-1 w-full max-w-sm">
                                    <span className="text-[10px] font-black text-[#C41C1C] uppercase tracking-widest ml-1">Sehat AI</span>
                                    <div className="bg-slate-50 rounded-2xl rounded-tl-sm p-4 text-slate-800 font-medium inline-block w-full sm:w-auto">
                                        Is this an emergency?
                                    </div>

                                    {/* Urgency Cards */}
                                    {currentStep === 3 && (
                                        <div className="space-y-3 mt-2 animate-in fade-in duration-500">
                                            <div
                                                onClick={() => handleUrgencySelect('Urgent')}
                                                className={`p-4 rounded-2xl border cursor-pointer transition-all flex items-center gap-4 ${urgency === 'Urgent'
                                                        ? 'border-[#C41C1C] bg-red-50/50'
                                                        : 'border-slate-200 bg-white hover:border-slate-300 hover:bg-slate-50'
                                                    }`}
                                            >
                                                <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${urgency === 'Urgent' ? 'bg-white text-[#C41C1C] shadow-sm' : 'bg-slate-100 text-slate-500'}`}>
                                                    <AlertTriangle size={18} className={urgency === 'Urgent' ? 'fill-current' : ''} />
                                                </div>
                                                <div>
                                                    <h4 className={`font-bold ${urgency === 'Urgent' ? 'text-slate-900' : 'text-slate-700'}`}>Urgent</h4>
                                                    <p className="text-xs text-slate-500 font-medium mt-0.5">Needed within 6 hours</p>
                                                </div>
                                            </div>

                                            <div
                                                onClick={() => handleUrgencySelect('Standard')}
                                                className={`p-4 rounded-2xl border cursor-pointer transition-all flex items-center gap-4 ${urgency === 'Standard'
                                                        ? 'border-[#C41C1C] bg-red-50/50'
                                                        : 'border-slate-200 bg-white hover:border-slate-300 hover:bg-slate-50'
                                                    }`}
                                            >
                                                <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${urgency === 'Standard' ? 'bg-white text-[#C41C1C] shadow-sm' : 'bg-slate-100 text-slate-500'}`}>
                                                    <Clock size={18} />
                                                </div>
                                                <div>
                                                    <h4 className={`font-bold ${urgency === 'Standard' ? 'text-slate-900' : 'text-slate-700'}`}>Standard</h4>
                                                    <p className="text-xs text-slate-500 font-medium mt-0.5">Needed within 24 hours</p>
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* USER MSG 3: Selected Urgency */}
                        {currentStep >= 4 && urgency && (
                            <div className="flex gap-4 max-w-2xl ml-auto justify-end animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="space-y-1 flex flex-col items-end">
                                    <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest mr-1">You</span>
                                    <div className="bg-[#C41C1C] text-white rounded-2xl rounded-tr-sm p-4 h-14 flex items-center justify-center text-sm font-bold shadow-md shadow-red-200">
                                        {urgency}
                                    </div>
                                </div>
                                <div className="w-10 h-10 rounded-full bg-orange-100 overflow-hidden shrink-0 mt-5 border border-slate-100 shadow-sm flex items-center justify-center text-orange-500 font-bold">
                                    You
                                </div>
                            </div>
                        )}

                        {/* BOT MSG 4: Ready */}
                        {currentStep >= 4 && (
                            <div className="flex gap-4 max-w-2xl animate-in fade-in slide-in-from-bottom-4 duration-500">
                                <div className="w-10 h-10 rounded-full bg-red-50 flex items-center justify-center shrink-0 mt-6 shadow-sm">
                                    <Bot size={20} className="text-[#C41C1C]" />
                                </div>
                                <div className="space-y-3 flex-1 w-full max-w-sm">
                                    <span className="text-[10px] font-black text-[#C41C1C] uppercase tracking-widest ml-1">Sehat AI</span>
                                    <div className="bg-slate-50 rounded-2xl rounded-tl-sm p-4 text-slate-800 font-medium inline-block w-full sm:w-auto">
                                        Got it. Your request is ready to be broadcasted to nearby donors!
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* Invisible div for scrolling to bottom */}
                        <div ref={chatEndRef} className="h-4" />
                    </div>

                    {/* Sticky Bottom Summary & Action Bar (Only show when step >= 4) */}
                    <div className={`absolute bottom-0 left-0 w-full bg-white border-t border-slate-100 p-6 flex flex-col items-center z-10 transition-transform duration-500 ${currentStep >= 4 ? 'translate-y-0 opacity-100' : 'translate-y-full opacity-0 pointer-events-none'}`}>

                        {/* Dynamic Summary Pill */}
                        <div className="w-full max-w-2xl bg-white border border-slate-200 rounded-full px-5 py-3 mb-4 flex flex-wrap items-center justify-center sm:justify-start gap-4 sm:gap-6 shadow-sm">
                            <div className="flex items-center gap-2 text-sm">
                                <Droplet size={14} className="text-[#C41C1C]" fill="currentColor" />
                                <span className="font-bold text-slate-900">{bloodGroup} <span className="font-medium text-slate-500 hidden sm:inline">Blood</span></span>
                            </div>
                            <div className="w-px h-4 bg-slate-200 hidden sm:block"></div>
                            <div className="flex items-center gap-2 text-sm">
                                <MapPin size={14} className="text-slate-400" />
                                <span className="font-bold text-slate-900">{city}</span>
                            </div>
                            {urgency === 'Urgent' && (
                                <>
                                    <div className="w-px h-4 bg-slate-200 hidden sm:block"></div>
                                    <div className="flex items-center gap-1.5 text-[10px] font-black tracking-widest uppercase text-[#C41C1C]">
                                        <AlertTriangle size={12} fill="currentColor" />
                                        Urgent
                                    </div>
                                </>
                            )}
                        </div>

                        {/* Primary Action Button */}
                        <button
                            onClick={handleSubmit}
                            disabled={isSubmitting}
                            className="w-full max-w-2xl rounded-full bg-[#C41C1C] px-8 py-4 text-base font-bold text-white shadow-xl shadow-red-200 transition-all hover:bg-[#A01717] hover:-translate-y-1 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:translate-y-0"
                        >
                            {isSubmitting ? (
                                <>
                                    <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin shrink-0"></span>
                                    Broadcasting...
                                </>
                            ) : (
                                <>
                                    <Send size={18} /> Submit Blood Request
                                </>
                            )}
                        </button>

                        <p className="text-[10px] font-medium text-slate-400 mt-4 text-center">
                            By submitting, you agree to share your contact details with verified donors.
                        </p>
                    </div>

                </div>
            </main>
        </div>
    );
}
